name: hris_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  http: ^1.1.0
  logger: ^1.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/EARIST_Logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/EARIST_Logo.png
    - assets/images/EARIST.png
    - assets/icons/mail.svg
    - assets/icons/phone.svg
    - assets/icons/dashboard.svg
    - assets/icons/notification.svg
    - assets/icons/calendar.svg
    - assets/icons/settings.svg
    - assets/icons/log-out.svg
    - assets/icons/forms.svg
    - assets/icons/form.svg
    - assets/icons/home.svg
    - assets/icons/user.svg
    - assets/icons/clock.svg
    - assets/icons/calendar2.svg
    - assets/icons/payroll.svg
    - assets/icons/attendance.svg
    - assets/icons/request.svg
